# Generated by Django 5.2.7 on 2025-10-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('frameworks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_projeto', models.CharField(max_length=20, unique=True)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('tipo_sistema', models.CharField(choices=[('WEB', 'Web'), ('APP', 'Mobile'), ('API', 'API'), ('DESKTOP', 'Desktop'), ('EMB', 'Embarcado')], max_length=10)),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('HOMOLOG', 'Homologação'), ('PROD', 'Produção')], max_length=10)),
                ('plano_contratado', models.CharField(choices=[('PACOTE', 'Pacote'), ('PROJETO', 'Projeto'), ('HORA', 'Por Hora')], max_length=20)),
                ('plano_opcao', models.CharField(blank=True, max_length=50)),
                ('horas_contratadas', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status_projeto', models.CharField(default='EM_EXECUCAO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frameworks.framework')),
            ],
        ),
    ]
